language: java
services:
- postgresql
before_script:
- psql -c 'create database invoicify;' -U postgres
- psql -c "CREATE USER testuser WITH PASSWORD 'admin';" -U postgres
deploy:
  provider: heroku
  api_key:
    secure: h0z2qybEfrVSMvLO+H2ZsbzusMa0IyQmYyNFXKxVG/soB6K+DxsrwfFFnOxdKdQ/1mRYtE0YA5HrAMY6pCoBrtn5jUaX8m6mhhG/UrNQpg8QwfF7T5GYpDH3mj5ChQLXEAZoGVokKJ5kHnZEQcZOwCHSUOt0238cgwwCfYcKbauC2mrejl6p8xnGQHLQtV/M8nH2dQcaDB7pfhAe3Q2sN1TwPfLFd/2wB0u+mTkLosR+vUGMeYZe119azh77ew498kg2rPvg4OaswGAnFuflFoGkZhj1/OWog3rkHYsF7ztw1uiTUqbGyAKci2zwQUHJFBbwFvN4pU5XZRtJW5TPBluMax9HQEYicLsfS3yAVV0Qjz+KubGQgUCa47eUyXD47Q7VOopVJdUtgr4SQQXGoUkuDL0Pe4iG3D5lsnJjtK4OKR0ouO3C+bHX5xrKm1uACEO3X1/XeMgMUBH8WVC9aDm5GcWISIAXoujmUPvIq5ElAdd1crYK0i18htC6VYeQUAarZEW+AJ4+TA96A9A7BLuXwBXcbTkJpJxwBnEIaYM9Vx01qFzGzOLZiUQVxvRS9Nd3fx1X/o0DtwM/yOkV+lFTeA9NGG4tWTLlR3WoXEGMIqT6bc7LRolwKRmgsxsAuRyDgR2MMoW7mLbEW2HWmcHHIEoT1D7+HT2EPa9uA5g=
  app: invoicify-ally
